import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

/**
 * POST /api/qr/generate
 * Generate a new QR code for a client
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // 1. Authenticate user
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Usuario no autenticado' },
        { status: 401 }
      )
    }

    // 2. Get user profile
    const { data: userProfile, error: profileError } = await supabase
      .from('user_profiles')
      .select('id, tenant_id')
      .eq('user_id', user.id)
      .single()

    if (profileError || !userProfile) {
      return NextResponse.json(
        { error: 'Perfil de usuario no encontrado' },
        { status: 404 }
      )
    }

    // 3. Parse request body
    const body = await request.json()
    const {
      client_id,
      promotion_id,
      brand_id,
      qr_type = 'promotion',
      max_redemptions = 1,
      discount_type,
      discount_value,
      discount_description,
      valid_until,
      metadata = {}
    } = body

    if (!client_id) {
      return NextResponse.json(
        { error: 'client_id es requerido' },
        { status: 400 }
      )
    }

    // 4. Verify access to client
    // Check if user is the client or has admin/brand_manager role
    const { data: client } = await supabase
      .from('clients')
      .select('id, user_id, tenant_id')
      .eq('id', client_id)
      .single()

    if (!client) {
      return NextResponse.json(
        { error: 'Cliente no encontrado' },
        { status: 404 }
      )
    }

    // Check if user is the client owner
    const isClientOwner = client.user_id === user.id

    // Or has admin/brand_manager role
    const { data: roles } = await supabase
      .from('user_roles')
      .select('role, status')
      .eq('user_profile_id', userProfile.id)

    const hasAdminAccess = roles?.some(role =>
      role.status === 'active' && ['admin', 'brand_manager'].includes(role.role)
    )

    if (!isClientOwner && !hasAdminAccess) {
      return NextResponse.json(
        { error: 'No tiene permisos para generar QR para este cliente' },
        { status: 403 }
      )
    }

    // 5. Create QR code (code will be auto-generated by trigger)
    const { data: qrCode, error: createError } = await supabase
      .from('qr_codes')
      .insert({
        tenant_id: userProfile.tenant_id,
        client_id,
        promotion_id: promotion_id || null,
        brand_id: brand_id || null,
        qr_type,
        max_redemptions,
        discount_type: discount_type || null,
        discount_value: discount_value || null,
        discount_description: discount_description || null,
        valid_until: valid_until || null,
        metadata
      })
      .select(`
        id,
        code,
        qr_type,
        status,
        max_redemptions,
        discount_type,
        discount_value,
        discount_description,
        valid_from,
        valid_until,
        created_at
      `)
      .single()

    if (createError) {
      console.error('Error creating QR code:', createError)
      return NextResponse.json(
        { error: 'Error al crear codigo QR', details: createError.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      message: 'Codigo QR generado exitosamente',
      qr_code: qrCode
    }, { status: 201 })

  } catch (error) {
    console.error('Error in POST /api/qr/generate:', error)
    const errorMessage = error instanceof Error ? error.message : 'Error desconocido'

    return NextResponse.json(
      { error: 'Error interno del servidor', details: errorMessage },
      { status: 500 }
    )
  }
}

/**
 * GET /api/qr/generate
 * Get QR codes for the authenticated client
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()

    // 1. Authenticate user
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Usuario no autenticado' },
        { status: 401 }
      )
    }

    // 2. Get client linked to this user
    const { data: client, error: clientError } = await supabase
      .from('clients')
      .select('id')
      .eq('user_id', user.id)
      .single()

    if (clientError || !client) {
      return NextResponse.json(
        { error: 'Cliente no encontrado' },
        { status: 404 }
      )
    }

    // 3. Get QR codes
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '20')

    let query = supabase
      .from('qr_codes')
      .select(`
        id,
        code,
        qr_type,
        status,
        max_redemptions,
        redemption_count,
        discount_type,
        discount_value,
        discount_description,
        valid_from,
        valid_until,
        created_at,
        promotion:promotions(id, name),
        brand:brands(id, name, logo_url)
      `)
      .eq('client_id', client.id)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (status) {
      query = query.eq('status', status)
    }

    const { data: qrCodes, error: qrError } = await query

    if (qrError) {
      console.error('Error fetching QR codes:', qrError)
      return NextResponse.json(
        { error: 'Error al obtener codigos QR' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      qr_codes: qrCodes || [],
      total: qrCodes?.length || 0
    })

  } catch (error) {
    console.error('Error in GET /api/qr/generate:', error)
    const errorMessage = error instanceof Error ? error.message : 'Error desconocido'

    return NextResponse.json(
      { error: 'Error interno del servidor', details: errorMessage },
      { status: 500 }
    )
  }
}
