import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

/**
 * POST /api/qr/generate
 * Generate a new QR code for a client
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // 1. Authenticate user
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Usuario no autenticado' },
        { status: 401 }
      )
    }

    // 2. Get user profile
    const { data: userProfile, error: profileError } = await supabase
      .from('user_profiles')
      .select('id, tenant_id')
      .eq('user_id', user.id)
      .single()

    if (profileError || !userProfile) {
      return NextResponse.json(
        { error: 'Perfil de usuario no encontrado' },
        { status: 404 }
      )
    }

    // 3. Parse request body
    const body = await request.json()
    const {
      client_id,
      promotion_id,
      brand_id,
      qr_type = 'promotion',
      max_redemptions = 1,
      discount_type,
      discount_value,
      discount_description,
      valid_until,
      metadata = {}
    } = body

    if (!client_id) {
      return NextResponse.json(
        { error: 'client_id es requerido' },
        { status: 400 }
      )
    }

    // 4. Verify access to client
    // Check if user is the client or has admin/brand_manager role
    const { data: client } = await supabase
      .from('clients')
      .select('id, user_id, tenant_id')
      .eq('id', client_id)
      .single()

    if (!client) {
      return NextResponse.json(
        { error: 'Cliente no encontrado' },
        { status: 404 }
      )
    }

    // Check if user is the client owner
    const isClientOwner = client.user_id === user.id

    // Or has admin/brand_manager role
    const { data: roles } = await supabase
      .from('user_roles')
      .select('role, status')
      .eq('user_profile_id', userProfile.id)

    const hasAdminAccess = roles?.some(role =>
      role.status === 'active' && ['admin', 'brand_manager'].includes(role.role)
    )

    if (!isClientOwner && !hasAdminAccess) {
      return NextResponse.json(
        { error: 'No tiene permisos para generar QR para este cliente' },
        { status: 403 }
      )
    }

    // 5. If promotion_id provided, fetch and validate promotion
    let finalDiscountType = discount_type
    let finalDiscountValue = discount_value
    let finalDiscountDescription = discount_description
    let finalMaxRedemptions = max_redemptions

    if (promotion_id) {
      const { data: promotion, error: promotionError } = await supabase
        .from('promotions')
        .select('id, name, description, promotion_type, discount_percentage, discount_amount, usage_limit_per_client, status, start_date, end_date')
        .eq('id', promotion_id)
        .single()

      if (promotionError || !promotion) {
        return NextResponse.json(
          { error: 'Promoción no encontrada' },
          { status: 404 }
        )
      }

      // Validate promotion is active
      if (promotion.status !== 'active') {
        return NextResponse.json(
          { error: 'La promoción no está activa' },
          { status: 400 }
        )
      }

      // Validate promotion dates
      const now = new Date()
      const startDate = new Date(promotion.start_date)
      const endDate = new Date(promotion.end_date)

      if (now < startDate) {
        return NextResponse.json(
          { error: 'La promoción aún no ha iniciado' },
          { status: 400 }
        )
      }

      if (now > endDate) {
        return NextResponse.json(
          { error: 'La promoción ha expirado' },
          { status: 400 }
        )
      }

      // Auto-copy discount from promotion
      // Map promotion_type to discount_type
      if (promotion.promotion_type === 'discount_percentage') {
        finalDiscountType = 'percentage'
        finalDiscountValue = promotion.discount_percentage
      } else if (promotion.promotion_type === 'discount_amount') {
        finalDiscountType = 'fixed_amount'
        finalDiscountValue = promotion.discount_amount
      } else if (promotion.promotion_type === 'points_multiplier') {
        finalDiscountType = 'points'
        finalDiscountValue = promotion.discount_percentage // points multiplier
      } else if (promotion.promotion_type === 'free_product') {
        finalDiscountType = 'free_product'
        finalDiscountValue = 1
      }

      finalDiscountDescription = `${promotion.name}${promotion.description ? ': ' + promotion.description : ''}`

      // Auto-copy usage limit from promotion
      if (promotion.usage_limit_per_client) {
        finalMaxRedemptions = promotion.usage_limit_per_client
      }
    }

    // 6. Create QR code (code will be auto-generated by trigger)
    const { data: qrCode, error: createError } = await supabase
      .from('qr_codes')
      .insert({
        tenant_id: userProfile.tenant_id,
        client_id,
        promotion_id: promotion_id || null,
        brand_id: brand_id || null,
        qr_type,
        max_redemptions: finalMaxRedemptions,
        discount_type: finalDiscountType || null,
        discount_value: finalDiscountValue || null,
        discount_description: finalDiscountDescription || null,
        valid_until: valid_until || null,
        metadata
      })
      .select(`
        id,
        code,
        qr_type,
        status,
        max_redemptions,
        discount_type,
        discount_value,
        discount_description,
        valid_from,
        valid_until,
        created_at
      `)
      .single()

    if (createError) {
      console.error('Error creating QR code:', createError)
      return NextResponse.json(
        { error: 'Error al crear codigo QR', details: createError.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      message: 'Codigo QR generado exitosamente',
      qr_code: qrCode
    }, { status: 201 })

  } catch (error) {
    console.error('Error in POST /api/qr/generate:', error)
    const errorMessage = error instanceof Error ? error.message : 'Error desconocido'

    return NextResponse.json(
      { error: 'Error interno del servidor', details: errorMessage },
      { status: 500 }
    )
  }
}

/**
 * GET /api/qr/generate
 * Get QR codes for the authenticated client
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()

    // 1. Authenticate user
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Usuario no autenticado' },
        { status: 401 }
      )
    }

    // 2. Get client linked to this user
    const { data: client, error: clientError } = await supabase
      .from('clients')
      .select('id')
      .eq('user_id', user.id)
      .single()

    if (clientError || !client) {
      return NextResponse.json(
        { error: 'Cliente no encontrado' },
        { status: 404 }
      )
    }

    // 3. Get QR codes
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '20')

    let query = supabase
      .from('qr_codes')
      .select(`
        id,
        code,
        qr_type,
        status,
        max_redemptions,
        redemption_count,
        discount_type,
        discount_value,
        discount_description,
        valid_from,
        valid_until,
        created_at,
        promotion:promotions(id, name),
        brand:brands(id, name, logo_url)
      `)
      .eq('client_id', client.id)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (status) {
      query = query.eq('status', status)
    }

    const { data: qrCodes, error: qrError } = await query

    if (qrError) {
      console.error('Error fetching QR codes:', qrError)
      return NextResponse.json(
        { error: 'Error al obtener codigos QR' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      qr_codes: qrCodes || [],
      total: qrCodes?.length || 0
    })

  } catch (error) {
    console.error('Error in GET /api/qr/generate:', error)
    const errorMessage = error instanceof Error ? error.message : 'Error desconocido'

    return NextResponse.json(
      { error: 'Error interno del servidor', details: errorMessage },
      { status: 500 }
    )
  }
}
