import { NextRequest, NextResponse } from 'next/server';
import { createClient, createServiceClient } from '@/lib/supabase/server';
import { z } from 'zod';

const createZoneSchema = z.object({
  name: z.string().min(1, 'Nombre es requerido').max(255),
  code: z.string().min(1, 'Código es requerido').max(50),
  zone_type: z.enum(['country', 'region', 'state', 'city', 'district', 'custom'], 'Tipo de zona inválido'),
  description: z.string().optional(),
  country: z.string().length(2, 'Código de país debe tener 2 caracteres').default('MX'),
  state: z.string().max(100).optional(),
  cities: z.array(z.string()).optional(),
  postal_codes: z.array(z.string()).optional(),
  parent_zone_id: z.string().uuid('Zona padre inválida').optional().nullable(),
  sort_order: z.number().int().min(0).default(0),
  is_active: z.boolean().default(true)
});

export async function POST(request: NextRequest) {
  try {
    const supabase = createClient();

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 });
    }

    const { data: profile, error: profileError } = await supabase
      .from('user_profiles')
      .select('id, tenant_id')
      .eq('user_id', user.id)
      .single();

    if (profileError || !profile) {
      return NextResponse.json({ error: 'Perfil de usuario no encontrado' }, { status: 400 });
    }

    const { data: userRole, error: roleError } = await supabase
      .from('user_roles')
      .select('role')
      .eq('user_profile_id', profile.id)
      .eq('tenant_id', profile.tenant_id)
      .is('deleted_at', null)
      .single();

    if (roleError || !userRole || userRole.role !== 'admin') {
      return NextResponse.json({ error: 'Sin permisos para crear zonas' }, { status: 403 });
    }

    const body = await request.json();
    const validatedData = createZoneSchema.parse(body);

    const serviceSupabase = createServiceClient();

    // Validate parent_zone_id belongs to same tenant if provided
    if (validatedData.parent_zone_id) {
      const { data: parentZone, error: parentError } = await serviceSupabase
        .from('zones')
        .select('id')
        .eq('id', validatedData.parent_zone_id)
        .eq('tenant_id', profile.tenant_id)
        .is('deleted_at', null)
        .single();

      if (parentError || !parentZone) {
        return NextResponse.json(
          { error: 'Zona padre no encontrada o no válida' },
          { status: 400 }
        );
      }
    }

    // Check for duplicate code within tenant
    const { data: existingZone } = await serviceSupabase
      .from('zones')
      .select('id')
      .eq('tenant_id', profile.tenant_id)
      .eq('code', validatedData.code)
      .is('deleted_at', null)
      .maybeSingle();

    if (existingZone) {
      return NextResponse.json(
        { error: 'Ya existe una zona con ese código en este tenant' },
        { status: 400 }
      );
    }

    // public_id is auto-generated by DB sequence — do NOT include it
    const zoneData = {
      tenant_id: profile.tenant_id,
      name: validatedData.name,
      code: validatedData.code,
      zone_type: validatedData.zone_type,
      description: validatedData.description || null,
      country: validatedData.country,
      state: validatedData.state || null,
      cities: validatedData.cities || null,
      postal_codes: validatedData.postal_codes || null,
      parent_zone_id: validatedData.parent_zone_id || null,
      sort_order: validatedData.sort_order,
      is_active: validatedData.is_active,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    };

    const { data: newZone, error: insertError } = await serviceSupabase
      .from('zones')
      .insert(zoneData)
      .select('*')
      .single();

    if (insertError) {
      console.error('Error inserting zone:', insertError);
      return NextResponse.json(
        { error: 'Error al crear la zona' },
        { status: 500 }
      );
    }

    return NextResponse.json(
      { data: newZone, message: 'Zona creada exitosamente' },
      { status: 201 }
    );

  } catch (error) {
    console.error('Error in POST /api/admin/zones/create:', error);

    if (error instanceof z.ZodError) {
      return NextResponse.json(
        {
          error: 'Datos inválidos',
          details: error.issues.map(issue => ({
            field: issue.path.join('.'),
            message: issue.message
          }))
        },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({ error: 'Método no permitido' }, { status: 405 });
}
